// hotel-frontend/src/views/Dashboard.vue
<template>
  <section class="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
    <Card>
      <p class="text-sm text-gray-500">Total Rooms</p>
      <p class="text-3xl font-semibold mt-1">{{ totals.total }}</p>
    </Card>
    <Card>
      <p class="text-sm text-gray-500">Available</p>
      <p class="text-3xl font-semibold mt-1">{{ totals.available }}</p>
    </Card>
    <Card>
      <p class="text-sm text-gray-500">Booked</p>
      <p class="text-3xl font-semibold mt-1">{{ totals.booked }}</p>
    </Card>
  </section>

  <section class="grid lg:grid-cols-2 gap-5">
    <Card>
      <div class="flex items-center justify-between mb-3">
        <h3 class="text-lg font-semibold">Available now</h3>
        <RouterLink class="btn btn-ghost" to="/rooms">View all</RouterLink>
      </div>
      <div v-if="loading"><Loader/></div>
      <ul v-else class="divide-y divide-gray-100">
        <li v-for="r in available.slice(0,8)" :key="r.id" class="py-3 flex items-center justify-between">
          <div class="flex items-center gap-3">
            <span class="h-9 w-9 rounded-xl bg-gray-900 text-white grid place-items-center text-sm font-semibold">{{ r.number }}</span>
            <div>
              <p class="font-medium">{{ r.type }}</p>
              <p class="text-xs text-gray-500">€ {{ r.price }}</p>
            </div>
          </div>
          <StatusBadge status="AVAILABLE" />
        </li>
        <li v-if="available.length===0" class="text-sm text-gray-500">No rooms available.</li>
      </ul>
    </Card>

    <Card>
      <div class="flex items-center justify-between mb-3">
        <h3 class="text-lg font-semibold">Currently booked</h3>
        <RouterLink class="btn btn-ghost" to="/rooms">View all</RouterLink>
      </div>
      <div v-if="loading"><Loader/></div>
      <ul v-else class="divide-y divide-gray-100">
        <li v-for="r in booked.slice(0,8)" :key="r.id" class="py-3 flex items-center justify-between">
          <div class="flex items-center gap-3">
            <span class="h-9 w-9 rounded-xl bg-gray-900 text-white grid place-items-center text-sm font-semibold">{{ r.number }}</span>
            <div>
              <p class="font-medium">{{ r.type }}</p>
              <p class="text-xs text-gray-500">€ {{ r.price }}</p>
            </div>
          </div>
          <StatusBadge status="BOOKED" />
        </li>
        <li v-if="booked.length===0" class="text-sm text-gray-500">No rooms booked.</li>
      </ul>
    </Card>
  </section>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import Card from '@/components/ui/Card.vue'
import Loader from '@/components/ui/Loader.vue'
import StatusBadge from '@/components/ui/StatusBadge.vue'
import { listRooms } from '@/api/rooms'
import type { Room } from '@/types'

const rooms = ref<Room[]>([])
const loading = ref(false)

const available = computed(() => rooms.value.filter(r => r.status === 'AVAILABLE'))
const booked    = computed(() => rooms.value.filter(r => r.status === 'BOOKED'))
const totals = computed(() => ({
  total: rooms.value.length,
  available: available.value.length,
  booked: booked.value.length
}))

onMounted(load)
async function load() {
  loading.value = true
  try {
    const { data } = await listRooms()
    rooms.value = data
  } catch {
    // fallback dacă încă nu ai endpoint /rooms:
    rooms.value = [
      { id: 1, number: '101', type: 'STANDARD', price: 90, status: 'AVAILABLE' },
      { id: 2, number: '102', type: 'DELUXE',   price: 120, status: 'BOOKED' },
      { id: 3, number: '103', type: 'SUITE',    price: 180, status: 'AVAILABLE' },
      { id: 4, number: '104', type: 'STANDARD', price: 95, status: 'BOOKED' }
    ] as Room[]
  } finally { loading.value = false }
}
</script>

// react-frontend/src/components/Dashboard.js
import React, { useState, useEffect } from 'react';
import { roomApi, employeeApi, guestApi } from '../api/endpoints';

const Dashboard = () => {
    const [stats, setStats] = useState({
        rooms: { total: 0, available: 0, booked: 0, maintenance: 0 },
        employees: [],
        guests: []
    });
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        loadDashboardData();
    }, []);

    const loadDashboardData = async () => {
        try {
            setLoading(true);
            const [rooms, employeeStats, guestStats] = await Promise.all([
                roomApi.getAll(),
                employeeApi.getAnalytics(),
                guestApi.getAnalytics()
            ]);

            // Handle paginated response from backend
            const roomData = rooms.data?.content || rooms.data || [];

            // Calculate room statistics based on status field
            const roomStats = {
                total: roomData.length,
                available: roomData.filter(r => r.status === 'AVAILABLE').length,
                booked: roomData.filter(r => r.status === 'BOOKED').length,
                maintenance: roomData.filter(r => r.status === 'MAINTENANCE').length
            };

            // Map backend property names (cnt) to frontend names (count)
            const employees = (employeeStats.data || []).map(stat => ({
                role: stat.role,
                count: stat.cnt || stat.count || 0
            }));

            const guests = (guestStats.data || []).map(stat => ({
                type: stat.type,
                count: stat.cnt || stat.count || 0
            }));

            setStats({
                rooms: roomStats,
                employees: employees,
                guests: guests
            });
        } catch (err) {
            console.error('Dashboard data fetch error:', err);
            setError(err.message || 'Failed to load dashboard data');
        } finally {
            setLoading(false);
        }
    };

    if (loading) return <div className="text-center">Loading dashboard data...</div>;
    if (error) return <div className="text-red-600">{error}</div>;

    return (
        <div className="space-y-6">
            <h1 className="text-3xl font-bold">Dashboard</h1>
            
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                <div className="bg-white p-6 rounded-lg shadow">
                    <h3 className="text-lg font-semibold text-gray-700">Total Rooms</h3>
                    <p className="text-3xl font-bold text-blue-600">{stats.rooms.total}</p>
                </div>
                <div className="bg-white p-6 rounded-lg shadow">
                    <h3 className="text-lg font-semibold text-gray-700">Available Rooms</h3>
                    <p className="text-3xl font-bold text-green-600">{stats.rooms.available}</p>
                </div>
                <div className="bg-white p-6 rounded-lg shadow">
                    <h3 className="text-lg font-semibold text-gray-700">Booked Rooms</h3>
                    <p className="text-3xl font-bold text-red-600">{stats.rooms.booked}</p>
                </div>
                <div className="bg-white p-6 rounded-lg shadow">
                    <h3 className="text-lg font-semibold text-gray-700">In Maintenance</h3>
                    <p className="text-3xl font-bold text-yellow-600">{stats.rooms.maintenance}</p>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="bg-white p-6 rounded-lg shadow">
                    <h2 className="text-xl font-semibold mb-4">Employee Distribution</h2>
                    <div className="space-y-4">
                        {stats.employees.map(stat => (
                            <div key={stat.role} className="flex justify-between items-center">
                                <span className="text-gray-600">{stat.role}</span>
                                <span className="text-lg font-semibold">{stat.count}</span>
                            </div>
                        ))}
                    </div>
                </div>

                <div className="bg-white p-6 rounded-lg shadow">
                    <h2 className="text-xl font-semibold mb-4">Guest Distribution by Room Type</h2>
                    <div className="space-y-4">
                        {stats.guests.map(stat => (
                            <div key={stat.type} className="flex justify-between items-center">
                                <span className="text-gray-600">{stat.type}</span>
                                <span className="text-lg font-semibold">{stat.count}</span>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Dashboard;
